[profile.default]
solc = "0.8.10"
bytecode_hash = "none"
optimizer_runs = 1000000
via_ir = false
runs = 100
gas_reports = ["ATokenVault"]

[fuzz]
max_test_rejects = 65536
runs = 256


[profile.intense.fuzz]
runs = 10000
